# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashcredit', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('benefactor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PayCredits', to='mpesa.Customer')),
            ],
            options={
                'verbose_name': 'PayCredits',
                'verbose_name_plural': 'PayCredits',
            },
        ),
    ]
