# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyShortCodeOrNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='mpesa.CompanyShortCodeOrNumber')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdentifierType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InitiatorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaCommandId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occassion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_url', models.CharField(blank=True, max_length=200, null=True)),
                ('validation_url', models.CharField(blank=True, max_length=200, null=True)),
                ('company_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CompanyShortCodeOrNumber', to='mpesa.CompanyShortCodeOrNumber')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='mpesa.InitiatorName')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transaction_description', models.CharField(max_length=200, null=True)),
                ('account_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_reference', to='mpesa.MpesaCommandId')),
                ('command_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_id', to='mpesa.MpesaCommandId')),
                ('identifier_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifier_type', to='mpesa.IdentifierType')),
                ('initiator_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='mpesa.InitiatorName')),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcode', to='mpesa.Occassion')),
                ('party_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_a', to='mpesa.CompanyShortCodeOrNumber')),
                ('party_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_b', to='mpesa.CompanyShortCodeOrNumber')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator_conversation_id', models.CharField(blank=True, max_length=200, null=True)),
                ('response_description', models.CharField(blank=True, max_length=200, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=200, null=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('response_code', models.CharField(blank=True, max_length=200, null=True)),
                ('result_description', models.CharField(blank=True, max_length=200, null=True)),
                ('result_code', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='mpesa.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='mpesa.TransactionType'),
        ),
    ]
