# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyShortCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InitiatorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaCommandId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('comments', models.CharField(max_length=200, null=True)),
                ('phoneno', models.IntegerField(null=True)),
                ('command_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_id', to='mpesa.MpesaCommandId')),
                ('initiator_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='mpesa.InitiatorName')),
                ('shortcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_code', to='mpesa.CompanyShortCode')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_feedbacks', models.CharField(blank=True, max_length=200)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='mpesa.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='mpesa.TransactionType'),
        ),
    ]
