# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='mpesa.CompanyShortCodeOrNumber')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_url', models.CharField(blank=True, max_length=200, null=True)),
                ('validation_url', models.CharField(blank=True, max_length=200, null=True)),
                ('company_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CompanyShortCodeOrNumber', to='mpesa.CompanyShortCodeOrNumber')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='mpesa.InitiatorName')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerName',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='partyA',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='partyB',
        ),
        migrations.AddField(
            model_name='transaction',
            name='party_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='party_a', to='mpesa.CompanyShortCodeOrNumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='party_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_b', to='mpesa.CompanyShortCodeOrNumber'),
        ),
        migrations.AddField(
            model_name='transactionresponse',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactionresponse',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactionresponse',
            name='response_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactionresponse',
            name='result_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactionresponse',
            name='result_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
