from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^get/token/$', Authenticate.as_view(),
        name="mpesa/token/request",),
    url(r'^b2b/transaction/$', CreateBToBTransaction.as_view(),
        name="create_b_2_b_transaction",),
    url(r'^b2c/transaction/$', CreateBToCTransaction.as_view(),
        name="create_b_2_c_transaction",),
    url(r'^register/c2b/url/$', RegisterCToBUrl.as_view(),
        name="register_c_2_b_url",),
    url(r'^accountbalance/transaction/$', CheckAccountBalance.as_view(),
        name="check_account_balance",),
    url(r'^check/transaction/status/$', CheckTransactionStatus.as_view(),
        name="check_transaction_status",),
    url(r'^reversal/transaction$', TransactionReversal.as_view(),
        name="transaction_reversal",),
    url(r'^lipanampesa/online/$', InitiateLipaNaMpesaTransaction.as_view(),
        name="initiate_lipa_na_mpesa_online_transaction",),
    url(r'^lipanampesa/online/transaction/status$',
        QueryLipaNaMpesaOnlineTransactionStatus.as_view(),
        name="query_lipa_na_mpesa_online_transaction_statuss",),
    url(r'^create/occassion/$', CreateOccassion.as_view(),
        name="create_occasion",),
    url(r'^create/mpesa/command/id/$', CreateMpesaCommandId.as_view(),
        name="create_mpesa_command_id",),
    url(r'^create/company/shortcodeornumber/$',
        CreateCompanyShortCodeOrNumber.as_view(),
        name="create_company_short_code_or_number",),
    url(r'^create/initiator/name/$', CreateInitiatorName.as_view(),
        name="create_initiator_name",),
    url(r'^create/transaction/type/$', CreateTransactionType.as_view(),
        name="create_transaction_type",),
    url(r'^create/customer/$', CreateCustomer.as_view(),
        name="create_customer",),
    url(r'^create/initiator/type/$', CreateInitiatorType.as_view(),
        name="create_initiator_type",),

    url(r'^occassion/detail/(?P<pk>\d+)/$',
        OccasionDetailAPIView.as_view(), name='thread'),
    url(r'^mpesa/commandid/detail/(?P<pk>\d+)/$',
        MpesaCommandIdDetailAPIView.as_view(), name='thread'),
    url(r'^mpesa/shortcodeornumber/detail/(?P<pk>\d+)/$',
        MpesaShortCodeOrNumberDetailAPIView.as_view(), name='thread'),
    url(r'^initiator/name/detail/(?P<pk>\d+)/$',
        InitiatorNameDetailAPIView.as_view(), name='thread'),
    url(r'^transaction/type/detail/(?P<pk>\d+)/$',
        TransactionTypeDetailAPIView.as_view(), name='thread'),
    url(r'^customer/detail/(?P<pk>\d+)/$',
        CustomerDetailAPIView.as_view(), name='thread'),
    url(r'^identifier/type/detail/(?P<pk>\d+)/$',
        IdentifierTypeDetailAPIView.as_view(), name='thread'),

    url(r'^occassion/list/$',
        OccasionListView.as_view(), name='occassion-list'),
    url(r'^mpesacommandid/list/$',
        MpesaCommandIdListView.as_view(), name='mpesa-commandid-list'),
    url(r'^shortcodeornumber/list/$',
        MpesaShortCodeOrNumberListView.as_view(),
        name='shortcodeornumber-list'),
    url(r'^initiatorname/list/$',
        InitiatorNameListView.as_view(), name='initiatorname-list'),
    url(r'^transactiontype/list/$',
        TransactionTypeListView.as_view(), name='transactiontype-list'),
    url(r'^customer/list/$',
        CustomerListView.as_view(), name='customer-list'),
    url(r'^identifiertype/list/$',
        IdentifierTypeListView.as_view(), name='identifiertype-list'),
    url(r'^transaction/list/$',
        TransactionListView.as_view(), name='transaction-list'),
    url(r'^transactionresponse/list/$',
        TransactionResponseListView.as_view(),
        name='transactionresponse-list'),
    url(r'^registration/list/$',
        RegistrationListView.as_view(), name='registration-list'),
]
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json'])
